"""initial_yogii_schema

Revision ID: 799ec06ed3d1
Revises: 
Create Date: 2026-09-26 03:20:59.633212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799ec06ed3d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index(op.f('ix_app_configurations_id'), 'app_configurations', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('artifact_location', sa.String(length=255), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_enc', sa.Text(), nullable=False),
    sa.Column('upi_id_enc', sa.Text(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('upi_id_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_lookup_hash', sa.String(length=64), nullable=True),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('merchant_category', sa.String(length=50), nullable=True),
    sa.Column('trust_level', sa.String(length=20), nullable=False),
    sa.Column('is_fictional_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_index(op.f('ix_recipients_phone_lookup_hash'), 'recipients', ['phone_lookup_hash'], unique=False)
    op.create_index(op.f('ix_recipients_upi_id_lookup_hash'), 'recipients', ['upi_id_lookup_hash'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_table('transaction_graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_node', sa.String(length=100), nullable=False),
    sa.Column('receiver_node', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_graph_edges_id'), 'transaction_graph_edges', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_graph_edges_receiver_node'), 'transaction_graph_edges', ['receiver_node'], unique=False)
    op.create_index(op.f('ix_transaction_graph_edges_sender_node'), 'transaction_graph_edges', ['sender_node'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name_enc', sa.Text(), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=False),
    sa.Column('email_enc', sa.Text(), nullable=False),
    sa.Column('upi_id_enc', sa.Text(), nullable=False),
    sa.Column('device_id_enc', sa.Text(), nullable=True),
    sa.Column('phone_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('email_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('upi_id_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('key_version', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email_lookup_hash'), 'users', ['email_lookup_hash'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_lookup_hash'), 'users', ['phone_lookup_hash'], unique=False)
    op.create_index(op.f('ix_users_upi_id_lookup_hash'), 'users', ['upi_id_lookup_hash'], unique=True)
    op.create_table('demo_payment_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number_enc', sa.Text(), nullable=True),
    sa.Column('simulated_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_payment_accounts_id'), 'demo_payment_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_demo_payment_accounts_user_id'), 'demo_payment_accounts', ['user_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('recipient_upi_lookup_hash', sa.String(length=64), nullable=False),
    sa.Column('recipient_upi_masked', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['demo_payment_accounts.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_id'), 'payment_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_idempotency_key'), 'payment_attempts', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_attempts_recipient_upi_lookup_hash'), 'payment_attempts', ['recipient_upi_lookup_hash'], unique=False)
    op.create_index(op.f('ix_payment_attempts_reference'), 'payment_attempts', ['reference'], unique=True)
    op.create_index(op.f('ix_payment_attempts_sender_account_id'), 'payment_attempts', ['sender_account_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_sender_user_id'), 'payment_attempts', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_state'), 'payment_attempts', ['state'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_attempt_id')
    )
    op.create_index(op.f('ix_feature_snapshots_id'), 'feature_snapshots', ['id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_attempt_id', sa.Integer(), nullable=False),
    sa.Column('raw_risk_score', sa.Float(), nullable=False),
    sa.Column('calibrated_probability', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason_codes_json', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_attempt_id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_feature_snapshots_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_payment_attempts_state'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_sender_user_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_sender_account_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_reference'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_recipient_upi_lookup_hash'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_idempotency_key'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_demo_payment_accounts_user_id'), table_name='demo_payment_accounts')
    op.drop_index(op.f('ix_demo_payment_accounts_id'), table_name='demo_payment_accounts')
    op.drop_table('demo_payment_accounts')
    op.drop_index(op.f('ix_users_upi_id_lookup_hash'), table_name='users')
    op.drop_index(op.f('ix_users_phone_lookup_hash'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_lookup_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transaction_graph_edges_sender_node'), table_name='transaction_graph_edges')
    op.drop_index(op.f('ix_transaction_graph_edges_receiver_node'), table_name='transaction_graph_edges')
    op.drop_index(op.f('ix_transaction_graph_edges_id'), table_name='transaction_graph_edges')
    op.drop_table('transaction_graph_edges')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_recipients_upi_id_lookup_hash'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_phone_lookup_hash'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_app_configurations_id'), table_name='app_configurations')
    op.drop_table('app_configurations')
    # ### end Alembic commands ###
